- payment-locking-samples/Hide_UPI_Section.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/payment-page-payment-locking/payment-locking-samples/Hide_UPI_Section.sh","text":"curl --location --request POST 'https://sandbox.juspay.in/session' \\\n--header 'Authorization: Basic base_64_encoded_api_key==' \\\n--header 'x-merchantid: your_merchant_id' \\\n--header 'Content-Type: application/json' \\\n--data-raw '{\n    \"order_id\": \"testing-order-one\",\n    \"amount\": \"1.0\",\n    \"customer_id\": \"testing-customer-one\",\n    \"customer_email\": \"test@mail.com\",\n    \"customer_phone\": \"9876543210\",\n    \"payment_page_client_id\": \"your_client_id\",\n    \"action\": \"paymentPage\",\n    \"return_url\": \"https://shop.merchant.com\",\n    \"description\": \"Complete your payment\",\n …
> CHANGE: At hyper-checkout/android/resources/payment-locking by Ankit Jain

- payout/order-create/account-ifsc.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/payout/order-create/account-ifsc.sh","text":"curl --location --request POST 'https://api.juspay.in/payout/merchant/v1/orders' \\\n-u your_api_key: \\\n--header 'Content-Type: application/json' \\\n--header 'x-merchantid: <merchant-id>' \\\n--data-raw '{\n    \"orderId\": \"e6J4OxzzbpJ1G2Lu\",\n    \"fulfillments\": [\n        {\n            \"preferredMethodList\": [\n                \"CFGEN_IMPS\"\n            ],\n            \"amount\": 1,\n            \"beneficiaryDetails\": {\n                \"details\": {\n                    \"name\": \"Taral Shah\",\n                    \"account\": \"026291800001191\",\n                    \"ifsc\" : \"YESB0000262\"\n                },\n …
> CHANGE: At payout/docs/integration/order-create by Aditya Kadrolkar

- webhooks/ready-for-fulfillment.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/juspay-payout/webhooks/ready-for-fulfillment.json","text":"{\n  \"value\": \"READY_FOR_FULFILLMENT\",\n  \"label\": \"ORDER\",\n  \"info\": {\n    \"updatedAt\": \"2020-05-29T07:24:57Z\",\n    \"status\": \"READY_FOR_FULFILLMENT\",\n    \"orderType\": \"FULFILL_ONLY\",\n    \"merchantOrderId\": \"6lQuvBOixfADPpmD\",\n    \"merchantCustomerId\": \"1421255\",\n    \"id\": \"95eb968ccdd4f2d9ef31c3e972ca40\",\n    \"createdAt\": \"2020-05-29T07:24:13Z\",\n    \"amount\": 10\n  },\n  \"id\": \"5ed06807a0f429e8891847811bd050\",\n  \"category\": \"INFO\"\n}\n","sha":"b099d9e5c142fca732a39ae9ef0b84be8b9964af"}]
> CHANGE: At payout/docs/integration/webhooks by Aditya Kadrolkar

- Wallet/delink-wallet/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/Wallet/refresh-all/response.json","text":"{\n    \"list\": [\n        {\n            \"wallet\": \"MOBIKWIK\",\n            \"token\": \"tk_e25c15anlciu9cn68b3mm0d82082d2245c15326\",\n            \"last_refreshed\": \"2023-09-11T08:29:47Z\",\n            \"juspay_bank_code\": \"JP_MOBIKWIK\",\n            \"object\": \"wallet_account\",\n            \"metadata\": {\n                \"mobile_number\": \"9999999999\"\n            },\n            \"id\": \"wlm_rQgGVT5GHV6ntbR1\",\n            \"current_balance\": 100,\n            \"gateway_reference_id\": null,\n            \"sub_details\": [\n                {\n                    \"payment_method\": \"MOBIKWIK\",\n …
> CHANGE: At api-reference/docs/express-checkout/refresh-all-wallets by Ramya Kanth

- Wallet/refresh-wallet/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/Wallet/refresh-wallet/response.json","text":"{\n    \"wallet\": \"MOBIKWIK\",\n    \"token\": \"tkn_bceo87bpefjwlbfcv86vq8bxiwyen3\",\n    \"last_refreshed\": \"2023-09-11T08:26:15.000Z\",\n    \"object\": \"wallet_account\",\n    \"id\": \"wlm_bBJb6i6bjhvgnc\",\n    \"current_balance\": 100,\n    \"sub_details\": [\n        {\n            \"payment_method\": \"MOBIKWIK\",\n            \"payment_method_type\": \"WALLET\",\n            \"last_refreshed\": \"2023-09-11T08:26:15Z\",\n            \"current_balance\": 100\n        }\n    ],\n    \"linked\": true\n}","sha":"3687d87d05cd746cd43dab69133a2d12d3e3caf3"}]
> CHANGE: At api-reference/docs/express-checkout/refresh-wallet by Ramya Kanth

- orders/create-order/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-global/orders/create-order/request.sh","text":"curl --location 'https://sandbox.juspay.in/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic e3thcGlrZXl9fTo=' \\\n--data-urlencode 'order_id=1692783824' \\\n--data-urlencode 'merchant_id=paypal' \\\n--data-urlencode 'payment_method_type=WALLET' \\\n--data-urlencode 'payment_method=OVO' \\\n--data-urlencode 'redirect_after_payment=true' \\\n--data-urlencode 'format=json'\n--data-urlencode 'order.order_id=ord_1590759422' \\\n--data-urlencode 'order.amount=1015.00' \\\n--data-urlencode 'order.currency=SGD' \\\n--data-urlencode 'order.customer_id=cst_1590759422' \\\n--data-urlencode …
> CHANGE: At paytm-gateway-configuration/docs/express-checkout/create-order-api by Vaibhav DSouza

- payments/card-txn/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-global/payments/card-txn/request.sh","text":"// A regular card transaction\ncurl -X POST https://api.juspay.in/txns \\\n-d \"order_id=:order_id\" \\\n-d \"merchant_id=:merchant_id\" \\\n-d \"payment_method_type=CARD\" \\\n-d \"payment_method=VISA\" \\\n-d \"card_number=4242424242424242\" \\\n-d \"card_exp_month=10\" \\\n-d \"card_exp_year=20\" \\\n-d \"name_on_card=Name\" \\\n-d \"card_security_code=111\" \\\n-d \"save_to_locker=true\" \\\n-d \"redirect_after_payment=true\" \\\n-d \"format=json\"\n\n// A Stored card transaction\ncurl -X POST https://api.juspay.in/txns \\\n-d \"order_id=:order_id\" \\\n-d \"merchant_id=:merchant_id\" \\\n-d \"payment_method_type=CARD\" \\\n-d …
> CHANGE: At paytm-gateway-configuration/docs/express-checkout/credit--debit-card-transaction by Vaibhav DSouza

- card/list-cards/request.sh
- card/list-cards/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-global/card/list-cards/request.sh","text":"curl -X GET https://api.juspay.in/cards?customer_id=guest_user \\\n-H your_api_key:","sha":"afb6167dc6725380b57f1be3ae7dd46f3b54fb2d"},{"text":"{\n  \"customer_id\": \"customer_id\",\n  \"merchantId\": \"merchant_id\",\n  \"cards\": [\n    {\n      \"card_token\": \"abec0ba2-3406-47c7-93a8-f40ac025a38e\",\n      \"card_reference\": \"1c2d4b0120f9afe86d102edb17e79ac9\",\n      \"card_number\": \"5123-XXXXXXXX-2346\",\n      \"card_isin\": \"512345\",\n      \"card_exp_year\": \"2025\",\n      \"card_exp_month\": \"12\",\n      \"card_type\": \"CREDIT\",\n      \"card_issuer\": \"JP MORGAN\",\n      \"card_brand\": \"MASTERCARD\",\n      \"nickname\": …
> CHANGE: At paytm-gateway-configuration/docs/express-checkout/list-stored-cards by Vaibhav DSouza

- orders/create-payments/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/orders/create-payments/request.sh","text":"curl --location 'https://api.juspay.in/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic Auth of <your-api-key>' \\\n--data-urlencode 'order.order_id=ord_1590759422' \\\n--data-urlencode 'order.amount=101550.00' \\\n--data-urlencode 'order.currency=INR' \\\n--data-urlencode 'order.customer_id=cst_1590759422' \\\n--data-urlencode 'order.return_url=https://merchant.in/payments' \\\n--data-urlencode 'merchant_id=<your-merchant-id>' \\\n--data-urlencode 'payment_method_type=CARD' \\\n--data-urlencode 'payment_method=VISA' \\\n--data-urlencode 'card_number=4242424242424242' \\\n--data-urlencode …
> CHANGE: At api-reference/docs/express-checkout/create-order-with-payments by Deepesh Maheshwari

- payment-locking-samples/Hide_UPI_Section.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/payment-page-payment-locking/payment-locking-samples/Hide_UPI_Section.sh","text":"curl --location --request POST 'https://api.juspay.in/session' \\\n--header 'Authorization: Basic base_64_encoded_api_key==' \\\n--header 'x-merchantid: your_merchant_id' \\\n--header 'Content-Type: application/json' \\\n--data-raw '{\n    \"order_id\": \"testing-order-one\",\n    \"amount\": \"1.0\",\n    \"customer_id\": \"testing-customer-one\",\n    \"customer_email\": \"test@mail.com\",\n    \"customer_phone\": \"9876543210\",\n    \"payment_page_client_id\": \"your_client_id\",\n    \"action\": \"paymentPage\",\n    \"return_url\": \"https://shop.merchant.com\",\n    \"description\": \"Complete your payment\",\n …
> CHANGE: At blog/android/resources/payment-locking by Arun Baskaran

- mandates/create-order/ecr-order.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/create-order/ecr-order.sh","text":"curl --location --request POST 'https://sandbox.juspay.in/session' \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization: Basic MkNFQkU4QjYyQkQ0MDkwOEMzNzNGQUNBRDRGNjA1Og==' \\\n--header 'version: 2023-08-01' \\\n--data-raw '{\n  \"order_id\": \"order1697020098a\",\n  \"amount\": \"1\",\n  \"customer_id\": \"cth_qYcqE4hVnwL2Esnk\",\n  \"customer_email\": \"juspay.jus@gmail.com\",\n  \"customer_phone\": \"6369288490\",\n  \"payment_page_client_id\": \"fortum\",\n  \"first_name\":\"Sim\",\n  \"action\": \"paymentPage\",\n  \"return_url\": \"https://juspay.in/\",\n  \"gateway_id\": \"12\",\n  \"order_type\" : \"TPV_PAYMENT\",\n …
> CHANGE: At hyper-checkout/web/mandates/registration-api-with-tpv-flow by Aklank Jain

- upi/collect.json
- upi/collect.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/upi/collect.sh","text":"curl -X POST https://api.juspay.in/txns \\\n-d \"order_id=:order_id\" \\\n-d \"merchant_id=:merchant_id\" \\\n-d \"payment_method_type=UPI\" \\\n-d \"payment_method=UPI\" \\\n-d \"txn_type=UPI_COLLECT\" \\\n-d \"upi_vpa=:vpa\" \\\n-d \"redirect_after_payment=true\" \\\n-d \"format=json\"","sha":"ce92fa4d8d0993bf1b8cbdc438572ddd58929250"},{"text":"{\n  \"order_id\": \":order_id\",\n  \"txn_id\": \":txn_id\",\n  \"status\": \"PENDING_VBV\",\n  \"payment\": {\n    \"authentication\": {\n      \"method\": \"GET\",\n      \"url\": \"https://api.juspay.in/pay/start/guest/8646a7a0xxxxxfa99995fec00340a507\"\n    }\n  }\n}","filePath":"https://raw.githubusercontent.com/juspay/jus …
> CHANGE: At api-reference/docs/express-checkout/upi-collect by Deepesh Maheshwari

- sample-payload/cards/emi-new/request.json
- sample-payload/cards/emi-saved/request.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/ec-headless-sample/sample-payload/cards/emi-new/request.json","text":"{\n    \"requestId\": \"eee6f65e-23dc-42e1-ad7c-ec3cddd64ac9\",\n    \"service\": \"in.juspay.hyperapi\",\n    \"payload\": {\n        \"action\": \"cardTxn\",\n        \"orderId\": \"hyperorder45314\",\n        \"clientAuthToken\": \"tkn_0e37edc631d647fdb606ab48ccfc4213\",\n        \"endUrls\": [\n            \"https:\\\\/\\\\/shop\\\\.merchant\\\\.com\\\\/payments\\\\/handleResponse.*\"\n        ],\n        \"paymentMethod\": \"MASTERCARD\",\n        \"cardNumber\": \"4622540011002200\",\n        \"cardExpMonth\": \"05\",\n        \"cardExpYear\": \"25\",\n        \"cardSecurityCode\": \"123\",\n        \"saveToLocker\": true,\n …
> CHANGE: At ec-headless/android/payloads/cards by Vivek Muraleedharan Nair

- offers/list/coupon.json
- offers/list/request.sh
- offers/list/without-coupon.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/offers/list/without-coupon.json","text":"{\n   \"best_offer_combinations\": [\n        {\n            \"payment_method_reference\": \"card_number_identifier\",\n            \"offers\": [\n                {\n                    \"offer_id\": \"72ac6b3f-626c-413d-b1cf-5c7bd2e60cf3\",\n                    \"cashback_amount\": \"0.00\",\n                    \"discount_amount\": \"10000.00\",\n                    \"merchant_discount_amount\": \"0.00\",\n                    \"total_offered_amount\": \"10000.00\"\n                }\n            ],\n            \"order_breakup\": {\n                \"order_amount\": \"12000.00\",\n                \"applicable_order_amount\": \"12000.00\",\n …
> CHANGE: At api-reference/docs/express-checkout/offer-list by Anasuya Chakraborty

- orders/create-order/moto-request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/orders/create-order/moto-request.sh","text":"curl --location 'https://sandbox.juspay.in/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchant-id: <merchant_id>' \\\n--header 'Authorization: Basic <API Key setup on Juspay dashboard>' \\\n--data-urlencode 'order.order_id=ord_jkbvgusvb' \\\n--data-urlencode 'order.customer_id=cust_169' \\\n--data-urlencode 'order.currency=INR' \\\n--data-urlencode 'payment_method_type=CARD' \\\n--data-urlencode 'card_number=5329xxxxxx72625' \\\n--data-urlencode 'card_exp_month=05' \\\n--data-urlencode 'card_exp_year=26' \\\n--data-urlencode 'format=json' \\\n--data-urlencode 'payment_method=MASTERCARD' \\\n--data-urlencode …
> CHANGE: At api-reference/docs/express-checkout/create-moto-order-with-payments by Japnit Kaur Sidhu

- orders/create-payments/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/orders/create-payments/request.sh","text":"curl --location 'https://api.juspay.in/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic Auth of <your-api-key>' \\\n--data-urlencode 'order.order_id=ord_1590759422' \\\n--data-urlencode 'order.amount=101550.00' \\\n--data-urlencode 'order.currency=INR' \\\n--data-urlencode 'order.customer_id=cst_1590759422' \\\n--data-urlencode 'order.return_url=https://merchant.in/payments' \\\n--data-urlencode 'merchant_id=<your-merchant-id>' \\\n--data-urlencode 'payment_method_type=CARD' \\\n--data-urlencode 'payment_method=VISA' \\\n--data-urlencode 'card_number=4242424242424242' \\\n--data-urlencode …
> CHANGE: At api-reference/docs/express-checkout/create-order-with-payments by Japnit Kaur Sidhu

- mandate-registration/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/mandate-samples/mandate-registration/request.sh","text":"curl --location --request POST 'https://api.juspay.in/session' \\\n    --header 'x-merchantid: yourMerchantId' \\\n    --header 'Authorization: Basic base64encodedkey==' \\\n    --header 'Content-Type: application/json' \\\n    --data-raw '{\n    \"amount\":\"10.00\",\n    \"order_id\":\"yourUniqueOrderId\",\n    \"customer_id\":\"yourUniqueCustId\",\n    \"customer_phone\":\"9876543210\",\n    \"customer_email\":\"dummyemail@gmail.com\",\n    \"payment_page_client_id\":\"picasso\",\n    \"return_url\": \"https://shop.merchant.com\",\n    \"action\":\"paymentPage\",\n    \"options.create_mandate\":\"OPTIONAL/REQUIRED\",\n …
> CHANGE: At hyper-checkout/web/mandates/mandate-registration by Aklank Jain

- offers/list/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/offers/list/request.sh","text":"curl --location 'https://api.juspay.in/v1/offers/list?emi=true' \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization: <API KEY>' \\\n--data-raw '{\n    \"order\": {\n        \"order_id\": \"SDEA5645\",\n        \"amount\": \"12000\",\n        \"currency\": \"INR\",\n        \"basket\": \"[{\\\"id\\\":\\\"id1\\\",\\\"unitPrice\\\":10000,\\\"quantity\\\":1},{\\\"id\\\":\\\"id2\\\",\\\"unitPrice\\\":2000,\\\"quantity\\\":1}]\",\n        \"amount_info\": \"{\\\"base_amount\\\":\\\"11000\\\",\\\"add_on_amounts\\\":[{\\\"name\\\":\\\"tax\\\",\\\"amount\\\":\\\"1000\\\"}]}\"\n    },\n    \"payment_method_info\": [\n        {\n …
> CHANGE: At api-reference/docs/express-checkout/offer-list by Pranesh Kumar D

- mandates/notification-status/response.json
[{"filePath":" https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/notification-status/response.json","text":"{\n  \"status\": \"FAILURE\",\n  \"source_object\": \"MANDATE\",\n  \"source_info\": {\n    \"txn_date\": \"1634057114\",\n    \"mandate.display_invoice_number\": \"INVN5Aqwx3rCu9e9ELfC\",\n    \"amount\": \"1\"\n  },\n  \"provider_response\": {\n    \"provider_ref_id\": \"IN0CA915121983\",\n    \"provider_response_code\": \"00\",\n    \"provider_response_message\": \"Your notification is successful\"\n  },\n  \"provider_name\": \"BILLDESK\",\n  \"object_reference_id\": \"2QNPw8KSbpHL122bNPgA04\",\n  \"object\": \"notification\",\n  \"notification_type\": \"SMS\",\n  \"mandate\": {\n    \"mandate_id\": \"4rKxSj3bNXs7RQcdtajQza\"\n  },\n …
> CHANGE: At api-reference/docs/express-checkout/notification-status-api by Ankit Jain

- juspay-api-samples/session/curl.shell
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/juspay-api-samples/juspay-api-samples/session/curl.shell","text":"curl --location --request POST 'https://smartgatewayuat.hdfcbank.com/v4/session' \\\n--header 'Authorization: Basic base_64_encoded_api_key==' \\\n--header 'x-merchantid: your_merchant_id' \\\n--header 'Content-Type: application/json' \\\n--data-raw '{\n    \"order_id\": \"testing-order-one\",\n    \"amount\": \"1.0\",\n    \"customer_id\": \"testing-customer-one\",\n    \"customer_email\": \"test@mail.com\",\n    \"customer_phone\": \"9876543210\",\n    \"payment_page_client_id\": \"your_client_id\",\n    \"action\": \"paymentPage\",\n    \"return_url\": \"https://shop.merchant.com\",\n    \"description\": \"Complete your payment\",\n …
> CHANGE: At smartgateway-api-reference/docs/apis/session by Prathamesh Ramesh Rane

- mandates/notification-status/response.json
[{"filePath":" https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/notification-status/response.json","text":"{\n  \"status\": \"SUCCESS\",\n  \"source_object\": \"MANDATE\",\n  \"source_info\": {\n    \"txn_date\": \"1634057114\",\n    \"mandate.display_invoice_number\": \"INVN5Aqwx3rCu9e9ELfC\",\n    \"amount\": \"1\"\n  },\n  \"provider_response\": {\n    \"provider_ref_id\": \"IN0CA915121983\",\n    \"provider_response_code\": \"00\",\n    \"provider_response_message\": \"Your notification is successful\"\n  },\n  \"provider_name\": \"BILLDESK\",\n  \"object_reference_id\": \"2QNPw8KSbpHL122bNPgA04\",\n  \"object\": \"notification\",\n  \"notification_type\": \"SMS\",\n  \"mandate\": {\n    \"mandate_id\": \"4rKxSj3bNXs7RQcdtajQza\"\n  },\n …
> CHANGE: At api-reference/docs/express-checkout/notification-status-api by Aklank Jain

- card/card-info/cvv-less.json
- card/card-info/dotp.json
- card/card-info/mandate.json
- card/card-info/request-dotp.sh
- card/card-info/request-mandate.sh
- card/card-info/request-tokenize.sh
- card/card-info/request.sh
- card/card-info/response.json
- card/card-info/tokenize.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/card/card-info/request.sh","text":"curl -X GET https://api.juspay.in/cardbins/405028700 \\\n-u your_api_key: ","sha":"c4f2883b57379b4d0eefe3392d50699968e3c7ce"},{"text":"curl -X GET https://api.juspay.in/cardbins/405028700?merchant_id=merchantId&options.check_mandate_support=true' \\\n-u your_api_key: ","filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/card/card-info/request-mandate.sh","sha":"49aec0d0f8c9156dfd8b88f06645c5f56d135e82"},{"text":"curl -X GET https://api.juspay.in/cardbins/405028700?merchant_id=merchantId&options.check_direct_otp_support=true' \\\n-u your_api_key: ","filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integra …
> CHANGE: At api-reference/docs/express-checkout/card-info by Udit Khandelwal

- snapmint/CreateTxns
Adding Create API request for snapmint API
> Create CreateTxns API

- snapmint/SDKPaylaod
Adding Process payload for the SDK merchants
> SDK Process payload

- orders/create-order/moto-request.sh
- orders/create-payments/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/orders/create-payments/request.sh","text":"curl --location 'https://smartgateway.hdfcbank.com/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic Auth of <your-api-key>' \\\n--data-urlencode 'order.order_id=ord_1590759422' \\\n--data-urlencode 'order.amount=101550.00' \\\n--data-urlencode 'order.currency=INR' \\\n--data-urlencode 'order.customer_id=cst_1590759422' \\\n--data-urlencode 'order.return_url=https://merchant.in/payments' \\\n--data-urlencode 'merchant_id=<your-merchant-id>' \\\n--data-urlencode 'payment_method_type=CARD' \\\n--data-urlencode 'payment_method=VISA' \\\n--data-urlencode 'card_number=4242424242424242' …
> CHANGE: At airline-integration/docs/overview/create-order-with-payments by Advait Mahesh

- mandates/execution/request-session.sh
- mandates/execution/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/execution/request-session.sh","text":"curl --location 'https://api.juspay.in/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic <base64 of key:>' \\\n--data-urlencode 'order.order_id=unique_order_id' \\\n--data-urlencode 'order.amount=1.00' \\\n--data-urlencode 'order.customer_id=customer_id' \\\n--data-urlencode 'merchant_id=merchantid' \\\n--data-urlencode 'mandate_id=mandate_id' \\\n--data-urlencode 'mandate.execution_date=1622369936' \\\n--data-urlencode 'format=json'","sha":"d031071e55acb89a6f4b803a1af009d5879695ce"},{"text":"{\n  \"txn_uuid\": \"eulmN9X8JpeC7qK6AJq\",\n  \"txn_id\": \"merchant_id-order_id-1\",\n  \"status\": …
> CHANGE: At hyper-checkout/web/mandates/mandate-execution-api by Bhagat Muskan

- add-ons/payment-links/request.sh
- add-ons/payment-links/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/add-ons/payment-links/request.sh","text":"curl --location 'https://sandbox.juspay.in/session' \\\n--header 'origin: https://sandbox.juspay.in' \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization: Basic *********************API_KEY' \\\n--data-raw '{\n   \"mobile_country_code\": \"+91\",\n   \"payment_page_client_id\": \"picasso\",\n   \"amount\": 100,\n   \"currency\": \"INR\",\n   \"action\": \"paymentPage\", \n   \"customer_email\": \"asdf@gmail.com\",\n   \"customer_phone\": \"8888899999\",\n   \"first_name\": \"John\",\n   \"last_name\" : \"Doe\",\n   \"description\": \"This is Payment Description.\",\n   \"customer_id\": \"customer_id\",\n   \"order_id\": …
> CHANGE: At add-ons/docs/payment-links/payment-links--upi-deep-links by Manish Bhadauria

- mandates/webhook/txn/success.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/webhook/txn/success.json","text":"{\n  \"id\": \"evt_V2_4b83ba211443b53fc020d4c\",\n  \"event_name\": \"ORDER_SUCCEEDED\",\n  \"date_created\": \"2021-03-20T07:48:31Z\",\n  \"content\": {\n    \"order\": {\n      \"udf9\": \"\",\n      \"udf8\": \"\",\n      \"udf7\": \"\",\n      \"udf6\": \"\",\n      \"udf5\": \"\",\n      \"udf4\": \"\",\n      \"udf3\": \"\",\n      \"udf2\": \"\",\n      \"udf10\": \"\",\n      \"udf1\": \"\",\n      \"txn_uuid\": \"eulmy******y1Syy\",\n      \"txn_id\": \"juspay-2348******3498-1\",\n      \"txn_detail\": {\n        \"txn_uuid\": \"eulmy******y1Syy\",\n        \"txn_object_type\": \"EMANDATE_PAYMENT\",\n        \"txn_id\": …
> CHANGE: At upi-autopay/docs/how-to-integrate/webhooks by Prabu M

- expresscheckout-dotnet-framework-sdk/App_Start/BundleConfig.cs
- expresscheckout-dotnet-framework-sdk/Areas/HelpPage/Views/_ViewStart.cshtml
- expresscheckout-dotnet-framework-sdk/Controllers/InitiateJuspayPaymentController.cs
- expresscheckout-dotnet-framework-sdk/DotnetServer.csproj
- expresscheckout-dotnet-framework-sdk/Global.asax.cs
- expresscheckout-dotnet-framework-sdk/Web.config
- expresscheckout-dotnet-framework-sdk/packages.config
- expresscheckout-dotnet-sdk/Init.cs
- expresscheckout-dotnet-sdk/README.md
- expresscheckout-dotnet-sdk/dotnet_server.csproj
Upgraded expresscheckout sdk to  [2.0.4](https://www.nuget.org/packages/expresscheckout#releasenotes-body-tab)
> expresscheckout 2.0.4

- twid/order-status/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/payment-method-integrations/twid/order-status/request.sh","text":"curl --location 'https://api.juspay.in/ecr/orders/<orderId> \\\n--header 'Authorization: Basic Auth'\n--header 'Version: 2024-01-01'","sha":"964854b21dcfc48f1e89e91452f6bebfe49cbe44"}]
> CHANGE: At twid-v2/docs/twid-v2/modifications-in-order-status-response by Srikanth Mitra

- sample-payload/displaying-options/get-upi-mandate/request.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/ec-headless-sample/sample-payload/displaying-options/get-upi-mandate/request.json","text":"{\n    \"requestId\": \"eee6f65e-23dc-42e1-ad7c-ec3cddd64ac9\",\n    \"service\": \"in.juspay.hyperapi\",\n    \"payload\": {\n        \"action\": \"upiTxn\",\n        \"orderId\": \"hyperorder45314\",\n        \"getAvailableApps\": true,\n        \"getMandateApps\": true\n    }\n}","sha":"fa434cf69a645e0cfe25c716ecca5e2af779de27"}]
> CHANGE: At upi-autopay/docs/how-to-integrate/juspay-sdk-getmandateapps-call by Prabu M

- mandates/create-order/ecr-order.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/mandates/create-order/ecr-order.sh","text":"curl --location --request POST 'https://api.juspay.in/session' \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization: Basic base_64_encoded_api_key==' \\\n--header 'version: 2023-08-01' \\\n--data-raw '{\n  \"order_id\": \"order1697020098a\",\n  \"amount\": \"1\",\n  \"customer_id\": \"cth_qYcqE4hVnwL2Esnk\",\n  \"customer_email\": \"juspay.jus@gmail.com\",\n  \"customer_phone\": \"6369288490\",\n  \"payment_page_client_id\": \"your_client_id\",\n  \"first_name\":\"Sim\",\n  \"action\": \"paymentPage\",\n  \"return_url\": \"https://juspay.in/\",\n  \"order_type\" : \"TPV_PAYMENT\",\n  \"options.create_mandate\" : \"REQUIRED\",\n …
> CHANGE: At hyper-checkout/web/mandates-subscriptions/tpv--third-party-verification-flows by Bhagat Muskan

- sample-payload/displaying-options/card-list/request.json
- sample-payload/displaying-options/card-list/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/ec-headless-sample/sample-payload/displaying-options/card-list/request.json","text":"{\n  \"requestId\": \"bfc553f2-bb20-4bc6-b8a1-a4eea116d67c\",\n  \"service\": \"in.juspay.hyperapi\",\n  \"payload\": {\n      \"action\": \"cardList\",\n      \"clientAuthToken\": \"tkn_e715521dddd2409ea3febd012107a92b\",\n      \"checkCvvLessSupport\": \"true\"\n  }\n}","sha":"036622130cd08f5f9570ef88fa2d46e0af13bf93"},{"text":"{\n    \"requestId\": \"bfc553f2-bb20-4bc6-b8a1-a4eea116d67c\",\n    \"service\": \"in.juspay.hyperapi\",\n    \"payload\": {\n        \"merchantId\": \"picasso\",\n        \"action\": \"cardList\",\n        \"customerId\": \"test_customer\",\n        \"cards\": [{\n                \"cardIsin\": …
> CHANGE: At ec-headless/android/payloads/display-payment-options by Deepesh Maheshwari

- sample-payload/displaying-options/cvv-less/request.json
- sample-payload/displaying-options/cvv-less/response.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/ec-headless-sample/sample-payload/displaying-options/cvv-less/request.json","text":"{\n  \"requestId\": \"bfc553f2-bb20-4bc6-b8a1-a4eea116d67c\",\n  \"service\": \"in.juspay.hyperapi\",\n  \"payload\": {\n      \"action\": \"cardList\",\n      \"clientAuthToken\": \"tkn_e715521dddd2409ea3febd012107a92b\",\n      \"checkCvvLessSupport\": \"true\"\n  }\n}","sha":"036622130cd08f5f9570ef88fa2d46e0af13bf93"},{"text":"{\n    \"requestId\": \"bfc553f2-bb20-4bc6-b8a1-a4eea116d67c\",\n    \"service\": \"in.juspay.hyperapi\",\n    \"payload\": {\n        \"merchantId\": \"picasso\",\n        \"action\": \"cardList\",\n        \"customerId\": \"test_customer\",\n        \"cards\": [{\n                \"cardIsin\": …
> CHANGE: At ec-headless/android/payloads/cvv-less-flow by Deepesh Maheshwari

- ec-headless-sample/nfc/nfcSupportChecksuccess.json
- ec-headless-sample/nfc/nfcSupportCheckunsupportSDK.json
- ec-headless-sample/nfc/nfcsupportcheckfalse.json
- ec-headless-sample/nfc/readNFCDetailsreq.json
- ec-headless-sample/nfc/readNFCSDKissue.json
- ec-headless-sample/nfc/readNFCnopermission.json
- ec-headless-sample/nfc/readNFCsuccess.json
- ec-headless-sample/nfc/readNFCtimeout.json
> Adding NFC payloads

- ec-headless-sample/offers/cardTxnreq.json
- ec-headless-sample/offers/cardTxnresponse.json
- ec-headless-sample/offers/upiTxnReq.json
- ec-headless-sample/offers/upiTxnResp.json
This PR is to add payloads for the Offers SDK .
> adding changes in the offers SDK payload

- ec-headless-sample/offers/WalletTxnreq.json
- ec-headless-sample/offers/nbTxnResp.json
- ec-headless-sample/offers/nbTxnreq.json
- ec-headless-sample/offers/upiIntentreq.json
- ec-headless-sample/offers/upiIntentresp.json
- ec-headless-sample/offers/walletTxnresp.json
Adding NB, Wallet TXn offer payloads
> Adding NB, Wallet TXn offer payloads

- code-samples/sample-response/order-status/request-encrypted.sh
- code-samples/sample-response/refunds/request-encrypted.sh
- code-samples/sample-response/session/curl.sh
[{"filePath":"https://github.com/juspay/juspay-sdk-integration-demo/blob/hdfc-sample-codes/code-samples/sample-response/session/curl.sh","text":"curl --location --request POST 'https://smartgatewayuat.hdfcbank.com/session' \\\n--header 'version: 2023-06-30' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchantid: merchant_id'\\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n--data-urlencode 'order_id=14183944763' \\\n--data-urlencode 'amount=100.00' \\\n--data-urlencode 'currency=INR' \\\n--data-urlencode 'customer_id=guest_user_101' \\\n--data-urlencode 'customer_email=customer@gmail.com' \\\n--data-urlencode 'customer_phone=9988665522' \\\n--data-urlencode 'product_id=prod-141833' \\\n--data-urlencode …
> CHANGE: At smartgateway-api-ref-basicauth/docs/apis/session by Aniket Lawaniya

- orders/create-order/moto-request.sh
- orders/create-order/request.sh
- orders/create-payments/request.sh
- orders/order-status/request.sh
- orders/refund-order/request.sh
- payments/card-txn/request.sh
- payments/nb-payment/request.sh
- payments/wallet-payment/request.sh
- upi/collect.sh
- upi/intent.sh
- upi/verify-vpa.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/payments/card-txn/request.sh","text":"// A regular card transaction\ncurl -X POST https://smartgateway.hdfcbank.com/txns \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchantid: merchant_id'\\\n--header 'x-customerid: customer_id'\\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n-d \"order_id=:order_id\" \\\n-d \"merchant_id=:merchant_id\" \\\n-d \"payment_method_type=CARD\" \\\n-d \"payment_method=VISA\" \\\n-d \"card_number=4242424242424242\" \\\n-d \"card_exp_month=10\" \\\n-d \"card_exp_year=20\" \\\n-d \"name_on_card=Name\" \\\n-d \"card_security_code=111\" \\\n-d \"save_to_locker=true\" \\\n-d \"tokenize=true\" \\\n-d …
> CHANGE: At smartgateway-tranportal-integration/docs/tranportal-integration/credit--debit-card-transaction by Debdeepa Karmakar

- ec-headless-sample/Lazypay/FailureAmountnoteligible.json
- ec-headless-sample/Lazypay/FailureOTPattemptsexceededcreate.json
- ec-headless-sample/Lazypay/Failure_Accountlocked.json
- ec-headless-sample/Lazypay/Failure_OTPWrongCreate.json
- ec-headless-sample/Lazypay/Failureresponse.json
- ec-headless-sample/Lazypay/LinkWalletSuccess.json
- ec-headless-sample/Lazypay/RefreshBalances.json
- ec-headless-sample/Lazypay/Refreshwalletsresponse.json
- ec-headless-sample/Lazypay/WalletTxnReq.json
- ec-headless-sample/Lazypay/createWallet.json
- ec-headless-sample/Lazypay/success.json
- ec-headless-sample/Lazypay/walletTxnResp.json
> LazyPay Payloads

- add-ons/payment-links/200-standard-link.json
- add-ons/payment-links/alt-request.sh
- add-ons/payment-links/new-request.sh
- add-ons/payment-links/new-response.json
[{"filePath":"https://github.com/juspay/juspay-sdk-integration-demo/blob/api-reference-hdfc/add-ons/payment-links/alt-request.sh","text":"curl --location --request POST 'https://smartgatewayuat.hdfcbank.com/session' \\\n--header 'Authorization: Basic base_64_encoded_api_key==' \\\n--header 'x-merchantid: your_merchant_id' \\\n--header 'Content-Type: application/json' \\\n--data-raw '{\n    \"order_id\": \"testing-order-one\",\n    \"amount\": \"2000.0\",\n    \"currency\" : \"INR\",\n    \"customer_id\": \"testing-customer-one\",\n    \"customer_email\": \"test@mail.com\",\n    \"customer_phone\": \"9876543210\",\n    \"payment_page_client_id\": \"your_client_id\",\n    \"action\": \"paymentPage\",\n    \"return_url\": \"https://shop.merchant.com\",\n    \"description\": \"Complete your …
> CHANGE: At smartgateway-payment-links/docs/payment-links-via-api/session-api--payment-links by Debdeepa Karmakar

- payments/payment-methods/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/payments/payment-methods/request.sh","text":"curl -X GET https://api.juspay.in/merchants/guest/paymentmethods\n\ncurl -X GET https://api.juspay.in/merchants/guest/paymentmethods?options.add_outage=true","sha":"6a60c7b42b64eeb20b292428e8a7d2c57bd5b66d"}]
> CHANGE: At outages/docs/outages/payment-methods-api-with-outage by Priyanga Kandasamy

- LOYLTYREWARDZ/ec-sdk/txn/dotp/refund_response.json
- LOYLTYREWARDZ/ec-sdk/txn/split/refund_response
- LOYLTYREWARDZ/ec-sdk/txn/split/refund_response.json
> LR-Documentation

- eligibilityfalse.json
> please approve 

- Surchargepayloads/gatewaybasedsurcharge.js
> surchargelogics.js

- Surchargepayloads/NBsurcharge.js
> NBsurcharge logic

- Surchargepayloads/walletpaylatersurcharge.js
wallet paylater surcharge logics
> wallet paylater surcharge logics

- Surchargepayloads/cardsurcharge.js
> card surcharge logics

- Surchargepayloads/UPIsurcharge.js
> UPIsurcharge

- Surchargepayloads/udfbasedsurcharge.js
> udf based surcharge logics

- Surchargepayloads/amountbasedsurcharge.js
> amount based surcharge logics

- Surchargepayloads/gatewayrefidsurcharge.js
gateway refid based surcharge logics
> gateway refid based surcharge logics

- Surchargewebhooksuccess.json
Surcharge webhook success payload
> Surcharge webhook success

- Surchargepayloads/webhooksfailed.json
> webhooks failed payload

- Surchargepayloads/refundwebhooks.json
> surcharge refund webhooks

- Surchargepayloads/webhookssurcharge.json
> webhooks surcharge

- enach_session_api_request
> Please approve

- sample-payload/enach/enach/request.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/ec-headless-sample/sample-payload/enach/enach/request.json","text":"{\n    \"requestId\": \"eee6f65e-23dc-42e1-ad7c-ec3cddd64ac9\",\n    \"service\": \"in.juspay.hyperapi\",\n    \"payload\": {\n        \"action\": \"enach\",\n        \"orderId\": \"hyperorder45314\",\n        \"clientAuthToken\": \"tkn_0e37edc631d647fdb606ab48ccfc4213\",\n        \"signature\": \"T9/9GGLY3sDRoYddAXaMaiD19t7lDDg76P5Q1DjRLTg2g==\",\n        \"orderDetails\": \"{\\\"order_id\\\":\\\"R5317229588\\\",\\\"merchant_id\\\": \\\"idea_preprod\\\",\\\"amount\\\": \\\"1.00\\\",\\\"customer_id\\\": \\\"1234567890\\\",\\\"options.create_mandate\\\": \\\"REQUIRED\\\",\\\"mandate.max_amount\\\": \\\"5000\\\",\\\"mandate.start_date\\\": …
> CHANGE: At enach/docs/how-to-integrate/nbtxn-process-payload-for-mandate by Prabu M

- jusbiz/authorization-webhook/request.sh
- jusbiz/authorization-webhook/response.json
- jusbiz/create-payout/request.sh
- jusbiz/create-payout/response.json
- jusbiz/delete-virtual-card/request.sh
- jusbiz/delete-virtual-card/response.json
- jusbiz/get-security-code/request.sh
- jusbiz/get-security-code/response.json
- jusbiz/health-check/request.sh
- jusbiz/token-status-check/request.sh
- jusbiz/token-status-check/response.json
Adding headless APIs for developer portal - request and response
> Jusbiz Headless APIs for developer portal

- EMIpayloads/orderstatusrequest.json
> order status request

- EMIpayloads/apitxnsrequest.sh
> API Txns request

- payment-locking/enableonlyNB.sh
- payment-locking/hide_NBBank.sh
- payment-locking/hide_Visa.sh
- payment-locking/hide_visaCredit.sh
- payment-locking/onlyCardCreditVisa.sh
- payment-locking/onlyCardCreditVisaPlatinum.sh
- payment-locking/onlyCardCreditVisaPlatinumICICI.sh
- payment-locking/onlyNBBank.sh
- payment-locking/onlycard_CreditCard.sh
Adding card and NB payloads for functionally possible combinations.
> Hdfc sample codes

- EMIpayloads/cardlessapirequest.sh
> cardlessapirequest

- EMIpayloads/cardlesssdkrequest.json
cardless process sdk request payload
> cardlesssdkrequest

- EMIpayloads/cardlesssdkrequest.json
> cardlesssdkrequest.json

- EMIpayloads/apiordercreate.sh
> apiordercreate

- EMIpayloads/apicreateorderresponse.json
> apicreateorderresponse

- EMIpayloads/stdapitxnsrequest.sh
> stdapitxnsrequest

- EMIpayloads/stdcardlessapirequest.sh
> stdcardlessapirequest

- EMIpayloads/stdcardlesssdkrequest.json
> stdcardlesssdkrequest

- EMIpayloads/stdprocessrequest.json
> stdprocessrequest

- AdvanceEMIPayloads/APITxnRequest.sh
> APITxnRequest.sh

- AdvanceEMIPayloads/APITxnResponse.json
> APITxnResponse.json

- AdvanceEMIPayloads/ListEMIplans.sh
> ListEMIplans.sh

- AdvanceEMIPayloads/ListEmiResponse.json
> ListEmiResponse.json

- AdvanceEMIPayloads/SuccessOrderStatus.json
> SuccessOrderStatus.json

- AdvanceEMIPayloads/FailedOrderStatus.json
> FailedOrderStatus.json

- AdvanceEMIPayloads/SuccessWebhooks.json
> SuccessWebhooks.json

- AdvanceEMIPayloads/FailedWebhooks.json
> FailedWebhooks.json

- AdvanceEMIPayloads/ProcessResponse.json
> ProcessResponse.json

- orders/create-order/request.sh
- orders/create-payments/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/orders/create-order/request.sh","text":"curl --location --request POST 'https://smartgateway.hdfcbank.com/orders' \\\n--header 'version: 2023-06-30' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchantid: merchant_id'\\\n--header 'x-customerid: customer_id'\\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n--data-urlencode 'order_id=14183944763' \\\n--data-urlencode 'amount=100.00' \\\n--data-urlencode 'currency=INR' \\\n--data-urlencode 'customer_id=guest_user_101' \\\n--data-urlencode 'customer_email=customer@gmail.com' \\\n--data-urlencode 'customer_phone=9988665522' \\\n--data-urlencode 'product_id=prod-141833' \\\n--data-urlencode …
> CHANGE: At smartgateway-tranportal-integration/docs/tranportal-integration/create-order-api by Debdeepa Karmakar

- juspay-api-samples/session/request.json
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/juspay-api-samples/juspay-api-samples/session/request.json","text":"{\n  \"order_id\": \"testing-order-one\",\n  \"amount\": \"1.0\",\n  \"customer_id\": \"testing-customer-one\",\n  \"customer_email\": \"test@mail.com\",\n  \"customer_phone\": \"9876543210\",\n  \"payment_page_client_id\": \"yourClientId\",\n  \"action\": \"paymentPage\",\n  \"return_url\": \"https://shop.merchant.com\",\n  \"description\": \"Complete your payment\",\n  \"first_name\": \"John\",\n  \"last_name\": \"wick\",\n  \"metadata.JUSPAY:gateway_reference_id\": \"payu_test\"\n}","sha":"6fe0c5faed4ff0c99b6ef728c335328973cc653c"}]
> CHANGE: At smartgateway-api-reference/docs/apis/session by Debdeepa Karmakar

- Offers/failurewebhooks.json
> failurewebhooks.json

- orders/create-order/request.sh
- orders/order-status/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/orders/create-order/request.sh","text":"curl --location --request POST 'https://api.juspay.in/orders' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchantid: merchant_id'\\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n--data-urlencode 'order_id=14183944763' \\\n--data-urlencode 'amount=100.00' \\\n--data-urlencode 'currency=INR' \\\n--data-urlencode 'customer_id=guest_user_101' \\\n--data-urlencode 'customer_email=customer@gmail.com' \\\n--data-urlencode 'customer_phone=9988665522' \\\n--data-urlencode 'product_id=prod-141833' \\\n--data-urlencode 'return_url=http://shop.merchant.com/payments/handleResponse' \\\n--data-urlencode …
> CHANGE: At api-reference/docs/express-checkout/create-order-api by Maheti Mehra

- EMIpayloads/listemiplansresp.json
> listemiplansresp.json

- mandates/create-order/request-upi.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/mandates/create-order/request-upi.sh","text":"curl POST 'https://smartgatewayuat.hdfcbank.com/orders' \\\n-H 'x-merchantid: merchant' \\\n-H 'Content-Type: application/x-www-form-urlencoded'\\\n-d 'order_id=234823498237423894273498' \\\n-d 'amount=1.00' \\\n-d 'currency=INR' \\\n-d 'customer_id=cst_lz7emoo5okgav' \\\n-d 'customer_email=test@gmail.com' \\\n-d 'customer_phone=9818638469' \\\n-d 'billing_address_first_name=Name' \\\n-d 'billing_address_city=Bengaluru' \\\n-d 'shipping_address_city=Mumbai' \\\n-d 'shipping_address_first_name=Name' \\\n-d 'options.create_mandate=REQUIRED' \\\n-d 'mandate.amount_rule=VARIABLE' \\\n-d 'mandate.max_amount=1000.00' \\\n-d …
> CHANGE: At smartgateway-mandate-integration/docs/express-checkout/create-order--mandate by Aniket Lawaniya

- mandates/register/request-collect.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/mandates/register/request-collect.sh","text":"curl -X POST 'https://smartgatewayuat.hdfcbank.com/txns' \\\n-H 'Content-Type: application/x-www-form-urlencoded' \\\n-d 'order_id=234823498237423894273498' \\\n-d 'merchant_id=merchant' \\\n-d 'payment_method_type=UPI' \\\n-d 'payment_method=COLLECT' \\\n-d 'upi_vpa=9483407288@hdfc' \\\n-d 'redirect_after_payment=true' \\\n-d 'format=json' \\\n-d 'should_create_mandate=true' \\\n-d 'mandate_type=EMANDATE'\n","sha":"04965e446c4eba381be5dc0ff9b940e08f70377e"}]
> CHANGE: At smartgateway-mandate-integration/docs/express-checkout/mandate-registration-api by Aniket Lawaniya

- mandates/pause/request.sh
- mandates/resume/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/mandates/pause/request.sh","text":"curl --location --request POST 'http://smartgatewayuat.hdfcbank.com/mandates/7KKTSsVLcQjskY5F4moS5M' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic QjU3QTnwedgfqdeuiedkyNzhEQjQ0MTg4N0NEMDU6' \\\n--data-urlencode 'command=pause' \\\n--data-urlencode 'pause_end_date=1664200815' \\\n--data-urlencode 'pause_start_date=1664546405'","sha":"e78d842fbad80e81f5bfd482c5f1ab0a5740ed7b"},{"text":"curl --location --request POST 'http://smartgatewayuat.hdfcbank.com/mandates/7KKT3yu3LcQjskY5F4moS5M' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic …
> CHANGE: At smartgateway-mandate-integration/docs/express-checkout/pause-mandate by Aniket Lawaniya

- upi/collect.sh
- upi/intent.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/upi/collect.sh","text":"curl -X POST https://smartgateway.hdfcbank.com/txns \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n-d \"order_id=:order_id\" \\\n-d \"merchant_id=:merchant_id\" \\\n-d \"payment_method_type=UPI\" \\\n-d \"payment_method=UPI_COLLECT\" \\\n-d \"txn_type=UPI_COLLECT\" \\\n-d \"upi_vpa=:vpa\" \\\n-d \"redirect_after_payment=true\" \\\n-d \"format=json\"","sha":"b253d0ced33777d91ba87e23e0938556038555cd"},{"text":"curl -X POST https://smartgateway.hdfcbank.com/txns \\\n-H 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n-H 'Content-Type: application/x-www-form-urlencoded' \\\n-d …
> CHANGE: At smartgateway-tranportal-integration/docs/tranportal-integration/upi-collect by Prathamesh Ramesh Rane

- Offers/sdkprocessfailure.json
> sdkprocessfailure.json

- orders/create-order/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference/orders/create-order/request.sh","text":"curl --location --request POST 'https://api.juspay.in/orders' \\\n--header 'Content-Type: application/x-www-form-urlencoded' \\\n--header 'x-merchantid: merchant_id'\\\n--header 'Authorization: Basic QTA0QT*******ODg1Og==' \\\n--data-urlencode 'order_id=14183944763' \\\n--data-urlencode 'amount=100.00' \\\n--data-urlencode 'currency=INR' \\\n--data-urlencode 'customer_id=guest_user_101' \\\n--data-urlencode 'customer_email=customer@gmail.com' \\\n--data-urlencode 'customer_phone=9988665522' \\\n--data-urlencode 'product_id=prod-141833' \\\n--data-urlencode 'return_url=http://shop.merchant.com/payments/handleResponse' \\\n--data-urlencode …
> CHANGE: At api-reference/docs/express-checkout/create-order-api by Shreeshyam HS

- Offers/partialrefundweb.json
> partialrefundweb.json

- Offers/partialrefundsOS.json
> partialrefundsOS.json

- Offers/fullrefundweb.json
> fullrefundweb.json

- Offers/fullrefundOS.json
> fullrefundOS.json

- Offers/failureorderstatus.json
> failureorderstatus.json

- upi-intent-web/dependency.java
- upi-intent-web/onActivityResult.java
[{"filePath":"https://github.com/juspay/juspay-sdk-integration-demo/blob/juspay-api-samples/upi-intent-web/dependency.java","text":"implementation 'in.juspay:webview.sdk:1.0.3'\n","sha":"0bd3265fda559f8f41456325c7ca5a33bdde534e"},{"text":"@Override\nprotected void onActivityResult(int requestCode, int resultCode, Intentdata) { \n    super.onActivityResult(requestCode, resultCode, data);\n    if (requestCode == HyperWebViewServices.UPI_REQUEST_CODE) {\n        hyperWebViewServices.onActivityResult(requestCode, resultCode,data); \n    }\n}","filePath":"https://github.com/juspay/juspay-sdk-integration-demo/blob/juspay-api-samples/upi-intent-web/onActivityResult.java","sha":"e4a52e438fd074bb9b32498b93519e0fd610c165"}]
> CHANGE: At resources/docs/common-resources/upi-intent-support-on-webview by Rubai Mandal

- mandates/create-order/request-upi.sh
- mandates/execution/request.sh
- mandates/pause/request.sh
- mandates/register/request-collect.sh
- mandates/register/request-intent.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/mandates/register/request-collect.sh","text":"curl -X POST 'https://smartgatewayuat.hdfcbank.com/txns' \\\n-H 'Content-Type: application/x-www-form-urlencoded' \\\n-d 'order_id=234823498237423894273498' \\\n-d 'merchant_id=merchant' \\\n-d 'payment_method_type=UPI' \\\n-d 'payment_method=COLLECT' \\\n-d 'txn_type=UPI_COLLECT' \\\n-d 'upi_vpa=9483407288@hdfc' \\\n-d 'redirect_after_payment=true' \\\n-d 'format=json' \\\n-d 'should_create_mandate=true' \\\n-d 'mandate_type=EMANDATE'\n","sha":"e938348e4581566e321cf8e5085d1d5479f927c2"},{"text":"curl --location --request POST 'https://smartgatewayuat.hdfcbank.com/txns' \\\n--header 'Content-Type: application/x-www-form-urlencoded' …
> CHANGE: At smartgateway-mandate-integration/docs/express-checkout/mandate-registration-api by Prathamesh Ramesh Rane

- AdvanceEMIPayloads/sessionreq.sh
> sessionreq.sh

- AdvanceEMIPayloads/sessionresp.json
> sessionresp.json

- TPVPayloads/tpvPMapireq.sh
tpv Paymet Methods api request
> tpvPMapireq.sh

- TPVPayloads/tpvemandateapireq.sh
> tpvemandateapireq.sh

- TPVPayloads/tpvemandateapires.json
> tpvemandateapires.json

- TPVPayloads/PMapireq.sh
> PMapireq.sh

- TPVPayloads/UPIapitxnsreq.sh
> UPIapitxnsreq.sh

- TPVPayloads/sessionapireq.json
> sessionapireq.json

- TPVPayloads/NBprocessreq.json
> NBprocessreq.json

- TPVPayloads/succwebhook.json
> succwebhook.json

- TPVPayloads/failwebhook.json
> failwebhook.json

- TPVPayloads/refundreq.sh
> refundreq.sh

- TPVPayloads/failos.json
> failos.json

- TPVPayloads/succos.json
> succos.json

- TPVPayloads/refundwebhook.json
> refundwebhook.json

- TPVPayloads/refundos.json
> refundos.json

- TPVPayloads/emandateorderreq.sh
emandate order request payload
> emandateorderreq.sh

- AdvanceEMIPayloads/signatureprocess.json
> signatureprocess.json

- pm-payv3-forms/cards.html
> cards.html

- pm-payv3-forms/saved-cards.html
updation of EMI related params
> saved-cards.html

- payments/payment-methods/request.sh
[{"filePath":"https://raw.githubusercontent.com/juspay/juspay-sdk-integration-demo/api-reference-hdfc/payments/payment-methods/request.sh","text":"curl -X GET https://smartgateway.hdfcbank.com/merchants/guest/paymentmethods\n\ncurl -X GET https://smartgateway.hdfcbank.com/merchants/guest/paymentmethods?options.add_emandate_payment_methods=true\n\ncurl -X GET https://smartgateway.hdfcbank.com/merchants/guest/paymentmethods?options.add_supported_reference_ids=true\n\ncurl -X GET https://smartgateway.hdfcbank.com/merchants/guest/paymentmethods?options.add_outage=true","sha":"d0b46502bf54f14fed26efed85a94e152b706b7d"}]
> CHANGE: At smartgateway-tranportal-integration/docs/tranportal-integration/payment-methods by Debdeepa Karmakar

- TPVPayloads/tpvsessionapireq.json
> tpvsessionapireq.json

- upi/intent.sh
The UPI intent params were too cluttered hence prettified it.
> Update intent.sh update

- AdvanceEMIPayloads/OnlyEmi.json
> onlyemi.json

- Wallet/update-mobile/request.sh
> remove version

- Wallet/refresh-all/request.sh
> version removed

- mandates/create-order/ecr-order.sh
> Update ecr-order.sh - header version removed

- payments/payment-methods/emandatepmrequest.sh
> emandatepmrequest.sh

- card/tokenize/generatetokenreq.sh
> generatetokenreq.sh

- payments/nb-payment/requestglobal.sh
> requestglobal.sh

- payments/card-txn/newcardtxnreq.sh
> newcardtxnreq.sh

- payments/card-txn/storedcardtxn.sh
> storedcardtxn.sh

- webhooks/orderfailedwebhook.json
> orderfailedwebhook.json

- orders/responsewithauth.json
> responsewithauth.json

- mandates/order-api/globalordercreate.sh
> globalordercreate.sh

- mandates/order-api/create-order/globalautorefundpostsuccess.sh
global auto refund post success
> globalautorefundpostsuccess.sh

- Credoffer/Listofferapireq.sh
> Listofferapireq.sh

- Credoffer/listofferapires.json
> listofferapires.json

- Credoffer/failedos.json
> failedos.json

- Credoffer/failedwebhook.json
> failedwebhook.json

- Credoffer/successwebhook.json
> successwebhook.json

- Credoffer/successos.json
> successos.json

- twid/ec-sdk/eligibility-api/request.json
Updated with latest eligibility request
> Updated eligibility request.json

- outages/globaloutageresp.json
> globaloutageresp.json

- juspay-api-samples/session/requestglobal.json
> requestglobal.json

- simpl/api/order-create-request.sh
Updation of end points and edit of parameter values
> order-create-request.sh

- simpl/api/order-create-response.json
> order-create-response.json

- payout/account-validation/wallet.json
- payout/account-validation/wallet.sh
- payout/order-create/wallet.json
- payout/order-create/wallet.sh
- payout/order-status/request.sh
- payout/order-status/response.json
- payout/validation-status/request.sh
- payout/validation-status/response.json
> Brazil Doc Payout Request and Response
